branch-defaults:
  dev:
    environment: Fwd-env-1
  master:
    environment: null
global:
  application_name: FWD
  default_ec2_keyname: beanstalk
  default_platform: 64bit Amazon Linux 2015.03 v1.3.2 running PHP 5.5
  default_region: us-west-2
  profile: fwd
  sc: git
